NEXUSMODS_API_KEY = "API_KEY_HERE"
NEXUSMODS_CACHE_DIR = "nexus_moddata"
NEXUSMODS_CATEGORY_ID_TO_CATEGORY = {
    "22": "Buildings",
    "24": "Gameplay",
    "25": "Guilds/Factions",
    "26": "Body, Face, and Hair",
    "27": "Items and Objects - Player",
    "29": "Models and Textures",
    "35": "Quests and Adventures",
    "95": "Bug Fixes",
    "39": "Utilities",
    "28": "Miscellaneous",
    "97": "Presets - ENB and ReShade",
    "54": "Armour",
    "65": "Followers & Companions - Creatures",
    "74": "Environmental",
    "42": "User Interface",
    "78": "Immersion",
    "67": "Player Homes",
    "84": "Patches",
    "79": "Overhauls",
    "51": "Animation",
    "94": "Alchemy",
    "96": "Followers & Companions",
    "36": "Weapons and Armour",
    "55": "Weapons",
    "83": "Creatures and Mounts",
    "110": "Audio",
    "60": "Clothing and Accessories",
    "77": "Combat",
    "89": "Locations - New",
    "75": "Magic - Spells & Enchantments",
    "33": "NPC",
    "53": "Cities, Towns, Villages, and Hamlets",
    "62": "Visuals and Graphics",
    "93": "Magic - Gameplay",
    "90": "Locations - Vanilla",
    "85": "Items and Objects - World",
    "92": "Collectables, Treasure Hunts, and Puzzles",
    "104": "Shouts",
    "82": "Modders Resources",
    "103": "Armour - Shields",
    "88": "Dungeons",
    "100": "Crafting",
    "73": "Skills and Leveling",
    "34": "Races, Classes, and Birthsigns",
    "76": "Stealth",
    "109": "Character Presets",
	"40": "Cheats and God items",
	"108": "VR",
	"2": "2"
}